# The URL the site will be built for
base_url = "https://ludumdare.com"
title = "Ludum Dare"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

ignored_content = ["*.markdown"]

taxonomies = [
	# Games
	{name = "Platform"},
	{name = "Event"},
	{name = "Tags"},

	# Articles, FAQ
	{name = "Categories"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
